version: "3.9"

networks:
  traefik-network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NG_BUILD_CONFIGURATION: development
    container_name: R16a-frontend
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r16a-frontend.rule=Host(`r16a.ch`)"
      - "traefik.http.routers.r16a-frontend.entrypoints=websecure"
      - "traefik.http.routers.r16a-frontend.tls.certresolver=letsencrypt"