version: "3.9"

networks:
  traefik-network:
    external: true

services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        NG_BUILD_CONFIGURATION: production
    container_name: r16a-frontend
    networks:
      - traefik-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.r16a-frontend.rule=Host(`r16a.ch`)"
      - "traefik.http.routers.r16a-frontend.entrypoints=websecure"
      - "traefik.http.routers.r16a-frontend.tls.certresolver=letsencrypt"
      - "traefik.http.services.r16a-frontend.loadbalancer.server.port=80"